#Die simulation in dem ordner wurde ua noch mit einem dünnen inner pin contact gemacht



# Example macro file for TU1 simulation
# 
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4

# Geometry Options
# ----------------
# Here we simulate the detector, shielding and sample holder with rounded corners and cooling finger

  	#Detector Geometry Settings
  /geometry/TU1Detector/enable True

# Aktiviere TU1Detector und setze seine Längen
/geometry/TU1Detector/enable True
/geometry/TU1Detector/setLength/deadLayerFront  0.0 mm
/geometry/TU1Detector/setLength/deadLayerOutside  1. mm
/geometry/TU1Detector/setLength/deadLayerInside  0.2 mm
/geometry/TU1Detector/setLength/deadLayerBack  0.2 mm

/geometry/TU1Detector/setLength/distanceFromCap 7.78 mm
/geometry/TU1Detector/setLength/boreHoleDiameter 14 mm
/geometry/TU1Detector/setLength/boreHoleLength 65 mm
/geometry/TU1Detector/setLength/crystalLength 91.2 mm
/geometry/TU1Detector/setLength/crystalDiameter 91.2 mm
/geometry/TU1Detector/setLength/capThickness 1.6 mm
/geometry/TU1Detector/setLength/capThicknessside 2.5 mm

	#Shielding Settings + further Settings
/geometry/Shielding/enable True
/geometry/Shielding/setBool/simulateLid False
/geometry/Shielding/setBool/lidOn False
/geometry/Shielding/setLength/detectorLoc 10 cm
/geometry/TU1Detector/setBool/innerCopperRing True
/geometry/TU1Detector/setBool/innerCopperDisk True
/geometry/TU1Detector/setBool/innerCopperDiskbottom True
/geometry/TU1Detector/setBool/crystalHolderOn True

  	#Cooling Finger Settings
  /geometry/TU1Detector/setBool/coolingFingerOn True
  /geometry/Shielding/setBool/coolingFingerOn True
  	#Extended Source Settings

	#Extended Source Sphere
# /geometry/TU1Detector/setBool/extendedSampleOn True
#  /geometry/TU1Detector/setString/extendedSampleShape sphere
# /geometry/TU1Detector/setLength/sphereDiameter 1.528 cm
# /geometry/TU1Detector/setLength/sphereCenter 0.764 cm
#  /geometry/TU1Detector/setString/sampleMaterialName meteorit2_comp

       # RockSample 
#  /geometry/RockSample/enable True
#  /geometry/RockSample/setString/STLfileName /SHARE/raw/users/pichotta/TU1/Simulation/STL/Drelow_ascii.stl	  

# PEN Sample
/geometry/PENSample/enable True



# Initialize kernel
# -----------------
 /process/had/deex/correlatedGamma true
 /run/initialize


# Detector Response Parameters
# ----------------------------
# Energy resolution:
#   sigma/MeV = (A0 + A1*(E/MeV) + A2*(E/MeV)^2)^0.5
  /detectorResponse/setA0 25.00e-8
  /detectorResponse/setA1  1.07e-6
  /detectorResponse/setA2  0.00
#
# Trigger threshold:
# probability to trigger = 1.0 / (1 + exp((Evis-m_trigThreshold) / (m_trigWidth))),
# with Evis = Edep after energy deposition
  /detectorResponse/setTriggerThreshold 20 keV
  /detectorResponse/setTriggerWidth 5 keV
#


# Primary Generator Parameters
# ----------------------------
  /generator/directionMode isotropic
  /generator/posMode inLogicalVolume
  /generator/setLogicalVolumeName PENSample
# /gun/position 0 0 1 cm 
  
# Start the Runs 
# --------------
  /run/printProgress 10000
 /gun/particle ion
   
# /gun/ion 27 57  #57Co
# /run/fileName run57Co.root
# /run/beamOn 1000000
  
# /gun/ion 21 46 #46Sc
# /run/fileName run46Sc.root
# /run/beamOn 1000000
  
# /gun/ion 24 51 #51Cr
# /run/fileName run51Cr.root
# /run/beamOn 10000000

# /gun/ion 55 137 #137Cs
# /run/fileName run137Cs.root
# /run/beamOn 1000000
  
 #/gun/ion 11 22 #22Na
# /run/fileName run22Na.root
# /run/beamOn 1000000

# /gun/ion 13 26 #26Al 
# /run/fileName run26Al.root
# /run/beamOn 1000000

# /gun/ion 4 7 #7Be 
# /run/fileName run7Be.root
# /run/beamOn 10000000

/gun/ion 19 40 #40K 
/run/fileName /SHARE/groups/np/Geant4/TU1CSeibt250924/Simulation/projects/PENGranulate2509/run40K.root
/run/beamOn 10000000

# /gun/ion 25 54 #54Mn
# /run/fileName run54Mn.root
# /run/beamOn 10000000
  
#/gun/ion 81 208 #208Tl 
#/run/fileName /SHARE/groups/np/Geant4/TU1CSeibt250924/Simulation/projects/PENGranulate2509/run208Tl.root
#/run/beamOn 10000000

# /gun/ion 82 212 #212Pb 
# /run/fileName run212Pb.root
# /run/beamOn 10000000

# /gun/ion 83 214 #214Bi 
# /run/fileName run214Bi.root
# /run/beamOn 10000000

	# kann kein correlated gamma true?
# /gun/ion 89 228 #228Ac 
# /run/fileName run228Ac_test.root
# /run/beamOn 100000 #1000000
